### ISSUE TITLE
equivariance test

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [e3nn/e3nn#149]
Hello, 

This isuue comes from the discussion at https://github.com/FabianFuchsML/se3-transformer-public/issues/4 where Tess showed a small example on fitting output of representation list [(1, 0, 1), (1, 2, 1)]. 

I expect that when I rotate the input point clouds by R, the output feature should be like RMR.T where M is the 3*3 matrix (rank 2 tensor). However, it seems that it is not the case. I was wondering would it be possible for you to take a quick look to see what goes wrong? Thank you!

The code is modified from https://nbviewer.jupyter.org/gist/blondegeek/bc5e7b07f5469739669684ad8373f446/predict_ellipsoid_shape.ipynb

```
# Created at 2020-11-26
# Summary: equivariance test

import random

import numpy as np
import torch

import e3nn.point.data_helpers as dh
import e3nn.point.message_passing as mp
from e3nn import o3
from e3nn.networks import GatedConvParityNetwork
from e3nn.tensor import CartesianTensor

torch.set_default_dtype(torch.float64)
seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)


class Data(object):
    def __init__(self, n=200, r_cutoff=3.):
        self.n = n
        self.r_cutoff = r_cutoff
        self.Rs_in = [(1, 0, 1)]  # Scalar dummy input
        # Output will be a symmetric 3x3 matrix describing shape of ellipsoid
        self.Rs_out, self.Q = CartesianTensor(
            torch.rand(3, 3),  # dummy matrix just to get transformation matrix
            'ij=ji').to_irrep_transformation()
        # Rs_out: [(1, 0, 1), (1, 2, 1)]
        self.Q = self.Q.reshape(-1, 3, 3)
        self.points = self._gen_points()

    def _gen_points(self):
        points = torch.rand(self.n, 3) - 0.5
        points = points / points.norm(2, -1, keepdim=True)
        points -= torch.mean(points, dim=0)
        return points

    def _get_nx(self, rot=None):
        """ generate points on a ellopsoid """
        points = self.points  # self._gen_points()
        scale_matrix = torch.diag(torch.DoubleTensor([1, 3, 6]))  # np.array([[1,0,0],[0,2,0],[0,0,3]])

        points = torch.einsum('ij,jk,nk->ni', rot, scale_matrix, points)  # points @ scale_matrix.T @ rot.T
        rot_scale_matrix = torch.einsum('ij,kl,jl->ik', rot, rot,
                                        scale_matrix)  # rot_scale_matrix - rot@scale_matrix@rot.T
        irrep_label = CartesianTensor(rot_scale_matrix, 'ij=ji').to_irrep_tensor().tensor
        input = torch.ones(self.n, 1)  # Scalar inputs

        return input, points, irrep_label, rot_scale_matrix

    def get_data(self, rot, dev):
        input, points, irrep_label, rot_scale_matrix = self._get_nx(rot=rot)
        return dh.DataNeighbors(x=input, Rs_in=self.Rs_in, pos=points, r_max=self.r_cutoff,
                                irrep_label=irrep_label, cart_label=rot_scale_matrix).to(dev)


def equivariance_test(model, d, dev):
    n_norm = 1
    rot1, rot2 = o3.rot(0, 0, 0), o3.rot(90, 0, 0)
    print(f'rot2: {rot2}\n')
    d1 = d.get_data(rot1, dev)
    d2 = d.get_data(rot2, dev)

    out1 = model(d1.x / n_norm, d1.edge_index, d1.edge_attr, n_norm=n_norm)
    pred_cart1 = torch.einsum('aij,a->ij', d.Q.to(dev), out1[2])
    true_cart1 = d1.cart_label

    print('pred_cart1')
    print(pred_cart1)
    print()

    out2 = model(d2.x / n_norm, d2.edge_index, d2.edge_attr, n_norm=n_norm)
    pred_cart2 = torch.einsum('aij,a->ij', d.Q.to(dev), out2[2])
    true_cart2 = d2.cart_label

    print('pred_cart2')
    print(pred_cart2)
    print()

    print('true label rotate accordingly')
    print(true_cart2 - torch.einsum('ij,kl,jl->ik', rot2.to(dev), rot2.to(dev), true_cart1.to(dev)))
    print()

    print('prediction does not rotate accordingly. WHY NOT ZERO?')
    print(pred_cart2 - torch.einsum('ij,kl,jl->ik', rot2.to(dev), rot2.to(dev), pred_cart1.to(dev)))


if __name__ == '__main__':
    dev = 'cuda:0'
    d = Data(r_cutoff=0.3)

    model_kwargs = {
        "convolution": mp.Convolution,
        # Note this specifically uses the Convolution based on torch_geometric.nn.MessagePassing
        "Rs_in": d.Rs_in,
        "Rs_out": d.Rs_out,
        "mul": 4,  # This is essentially the number of channels per "L". Start small and go up from there.
        "layers": 4,
        "max_radius": d.r_cutoff,  # Should match whatever you used in DataNeighbors or DataPeriodicNeighbors
        "lmax": 2,  # lmax = 2 should be sufficient to start
        "number_of_basis": 5
    }

    model = GatedConvParityNetwork(**model_kwargs)

    opt = torch.optim.Adam(model.parameters(), lr=1e-3)
    loss_fn = torch.nn.modules.loss.MSELoss()
    n_norm = 10
    v = torch.rand((10, 3), device=dev)
    model.to(dev)
    equivariance_test(model, d, dev)
```

output is 
```
rot2: tensor([[-0.4481, -0.8940,  0.0000],
        [ 0.8940, -0.4481,  0.0000],
        [ 0.0000,  0.0000,  1.0000]])

pred_cart1
tensor([[ 0.0087,  0.0355,  0.0071],
        [ 0.0355, -0.0041,  0.0085],
        [ 0.0071,  0.0085,  0.0367]], device='cuda:0', grad_fn=<ViewBackward>)

pred_cart2
tensor([[-0.0300, -0.0161, -0.0108],
        [-0.0161,  0.0346,  0.0025],
        [-0.0108,  0.0025,  0.0367]], device='cuda:0', grad_fn=<ViewBackward>)

true label rotate accordingly
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

prediction does not rotate accordingly. WHY NOT ZERO?
tensor([[-5.6899e-02,  1.0300e-02,  4.9613e-16],
        [ 1.0300e-02,  5.6899e-02, -1.0365e-16],
        [ 4.9613e-16, -1.0365e-16, -4.9613e-15]], device='cuda:0',
       grad_fn=<SubBackward0>)

```

**Comment by blondegeek** [comment]
Hi @Chen-Cai-OSU,

First of all -- it's fantastic that you did an equivariance test and thanks for posting the issue. The problem here is not with the network but the data.

I don't yet understand why this is going on, but this notebook will show the problem with plots.
https://nbviewer.jupyter.org/gist/blondegeek/56a50536adece7ee15957397236cf516

Essentially, it seems that rotating in Cartesian space with `o3.rot(*angles)` and rotating in irrep space with `rs.rep(Rs_out, *angles)` are not doing quite same thing.

I'm going to tag @mariogeiger into this issue since I might not have time to revisit this until Wednesday.

Best!
Tess

**Comment by mariogeiger** [comment]
Hi, thanks for reporting, do you have a minimal code to reproduce the error?

**Comment by Chen-Cai-OSU** [comment]
Thank you both for quick reply!

@mariogeiger I cleaned the code a little bit in the previous post. The code is still a bit long. Let me explain what I am doing here. I am sampling 200 points from an ellipsoid whose principal axis are randomly rotated by rot. My goal is to use TFN to predict the ```rot@scale_matrix@rot.T``` for a new point cloud. The ```scale_matrix``` is fixed over different point clouds while ```rot``` is different across the different point clouds. All the data generation happens in the Data class. 

As it is a symmetric 3*3 matrix, I followed the example from Tess https://nbviewer.jupyter.org/gist/blondegeek/bc5e7b07f5469739669684ad8373f446/predict_ellipsoid_shape.ipynb. 

The first problem I encountered is for point clouds P1 and its rotated version P2 (rotate by o3.rot(90, 0, 0)), the output of model ```pred_cart1``` and ```pred_cart2``` does not satisfy
```
pred_cart2 = torch.einsum('ij,kl,jl->ik', rot2.to(dev), rot2.to(dev), pred_cart1.to(dev))
```

There are mainly three parts 1) generate data by Data Class 2) build the model and 3) equivariance test. I believe my code for 1) and 2) are quite standard. 3) happens in function ``` equivariance_test ```.  I hope the explanation is clear enough. Let me know if you need any further clarifications. Thanks!

**Comment by Chen-Cai-OSU** [comment]
What Tess metioned in the notebook https://nbviewer.jupyter.org/gist/blondegeek/56a50536adece7ee15957397236cf516 is about how rotation is handled. My understanding is that we can either a) apply rotation in cartesian coordinates (cell 50 in the notebook ```rot_d1_cart_label = torch.einsum('ij,kl,jl->ik', rot, rot, d1.cart_label)```) or b) in the irrep label (cell 53. ```rot_irrep_label = torch.einsum('ij,j->i', D, d1.irrep_label)```). It seems that b) has some issues here. But I don't know how this is related to my issue as what I am doing is more like a).

Going back and forth between rrep_tensor and cart_tensor seems tricky. I find ```to_irrep_tensor ``` and ```to_irrep_transformation()``` to be very attractive feature of ```e3nn```. (se3-transformer doesn't have that feature.)

Again, I am sorry about the slightly long example here. Thank you very much for your time!

**Comment by mariogeiger** [comment]
I reproduced the bug:

```python
import torch
from e3nn.tensor import CartesianTensor
from e3nn import rs, o3

Rs, Q = CartesianTensor(
    torch.rand(3, 3),  # dummy matrix just to get transformation matrix
    'ij=ji').to_irrep_transformation()
Q = Q.reshape(6, 3, 3)

abc = o3.rand_angles()
R = o3.rot(*abc)
D = rs.rep(Rs, *abc)

Q1 = torch.einsum('aik,ij,kl->ajl', Q, R, R)
Q2 = torch.einsum('ab,bij->aij', D, Q)

print((Q1 - Q2).numpy().round(3))
```

Let me see if I find the problem here

**Comment by mariogeiger** [comment]
The problem is in `o3.reduce` (supposing there is only one problem :-))

```python
import torch
from e3nn.tensor import CartesianTensor
from e3nn import rs, o3
from functools import partial
torch.set_default_dtype(torch.float64)

def D1(a, b, c):
    r = rs.rep(1, a, b, c)
    return o3.kron(r, r)

D2 = partial(rs.rep, 1)

n, A, rest = o3.reduce(D1, D2)

g = o3.rand_angles()

print((A @ D1(*g) @ A.T).numpy().round(2))
print(D2(*g).numpy().round(2))
```

**Comment by Chen-Cai-OSU** [comment]
> Let me see if I find the problem here

Hello, thank you for the quick fix. But I run into the following error when running your code.

```
Traceback (most recent call last):
  File "perm_playground/debug/mario.py", line 10, in <module>
    'ij=ji').to_irrep_transformation()
  File "/home/cai.507/Documents/DeepLearning/Signor/signor/graph/physics/e3nn/e3nn/tensor/cartesian_tensor.py", line 21, in to_irrep_transformation
    Rs_out, Q = rs.reduce_tensor(self.formula, **{i: Rs for i in old_indices})
  File "/home/cai.507/Documents/DeepLearning/Signor/signor/graph/physics/e3nn/e3nn/rs.py", line 1185, in reduce_tensor
    mul, B, representation = o3.reduce(representation, partial(rep, [(1, l, p)]), eps, has_parity)
  File "/home/cai.507/Documents/DeepLearning/Signor/signor/graph/physics/e3nn/e3nn/o3.py", line 526, in reduce
    assert (bigA @ D(*g) @ bigA.T - direct_sum(D_small(*g), D_rest(*g))).abs().max() < eps
RuntimeError: The size of tensor a (6) must match the size of tensor b (7) at non-singleton dimension 1
python perm_playground/debug/mario.py  4.02s user 3.52s system 476% cpu 1.585 total
```

**Comment by mariogeiger** [comment]
It's fixed now :rofl:

**Comment by Chen-Cai-OSU** [comment]
Awesome! I also achieved the equivariance now. Thank you so much!
