### ISSUE TITLE
🐛 [BUG] TypeError: spherical_harmonics() got an unexpected keyword argument 'x'

### ISSUE THREAD

**Issue by muammar** [e3nn/e3nn#250]
**Describe the bug**

The `tetris_gate.py` example needs this patch: 

```
--- orig/tetris_gate.py 2021-04-06 09:00:08.538070000 -0400
+++ tetris_gate.py      2021-04-06 09:00:30.253074000 -0400
@@ -105,8 +105,8 @@
         edge_src, edge_dst = radius_graph(x=data.pos, r=2.5, batch=data.batch)
         edge_vec = data.pos[edge_src] - data.pos[edge_dst]
         edge_attr = o3.spherical_harmonics(
-            l=self.irreps_sh,
-            x=edge_vec,
+            self.irreps_sh,
+            edge_vec,
             normalize=True,
             normalization='component'
         )
@@ -116,7 +116,6 @@
             end=2.5,
             number=3,
             basis='smooth_finite',
-            cutoff=True
         ) * 3**0.5

         x = scatter(edge_attr, edge_dst, dim=0).div(self.num_neighbors**0.5)
```

Otherwise, it fails with: 

```
  return torch._C._cuda_getDeviceCount() > 0
Network(
  (conv): Convolution(
    (fc): FullyConnectedNet(3, 256, 272)
    (tp): FullyConnectedTensorProduct(1x0e+1x1o+1x2e+1x3o x 1x0e+1x1o+1x2e+1x3o -> 32x0o+32x0e+16x1o+16x1e | 272 paths | 272 weights)
  )
  (gate): Gate (32x0o+32x0e+16x1o+16x1e -> 32x0e+8x1o+8x1e+8x1e+8x1o)
  (final): Convolution(
    (fc): FullyConnectedNet(3, 256, 304)
    (tp): FullyConnectedTensorProduct(32x0e+8x1o+16x1e+8x1o x 1x0e+1x1o+1x2e+1x3o -> 1x0o+6x0e | 304 paths | 304 weights)
  )
)
Traceback (most recent call last):
  File "tetris_gate.py", line 158, in <module>
    main()
  File "tetris_gate.py", line 140, in main
    pred = f(data)
  File "/home/elkhatim/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tetris_gate.py", line 107, in forward
    edge_attr = o3.spherical_harmonics(
TypeError: spherical_harmonics() got an unexpected keyword argument 'x'
```

**To Reproduce**

```
 wget https://raw.githubusercontent.com/e3nn/e3nn/main/examples/tetris_gate.py
python3 tetris_gate.py
```

**Expected behavior**

Training happens. Instead, there are errors with invalid keyword arguments. After applying the patch above, things work as expected. I wonder if those changes are correct though?

**Environment (please complete the following information):**
 - OS: Ubuntu.
 - python version: `Python 3.8.8`
 - python environment (commands are given for python interpreter):
   - e3nn version (`import e3nn; e3nn.__version__`): 0.2.4
   - pytorch version (`import torch; torch.__version__`) : 1.8.1+cu102
   - pytorch_geometric version (`import torch_geometric; torch_geometric.__version__`): `1.6.3`

**Additional context**
With the proposed patch above, the script finishes right?

```
  return torch._C._cuda_getDeviceCount() > 0
Network(
  (conv): Convolution(
    (fc): FullyConnectedNet(3, 256, 272)
    (tp): FullyConnectedTensorProduct(1x0e+1x1o+1x2e+1x3o x 1x0e+1x1o+1x2e+1x3o -> 32x0o+32x0e+16x1o+16x1e | 272 paths | 272 weights)
  )
  (gate): Gate (32x0o+32x0e+16x1o+16x1e -> 32x0e+8x1o+8x1e+8x1e+8x1o)
  (final): Convolution(
    (fc): FullyConnectedNet(3, 256, 304)
    (tp): FullyConnectedTensorProduct(32x0e+8x1o+16x1e+8x1o x 1x0e+1x1o+1x2e+1x3o -> 1x0o+6x0e | 304 paths | 304 weights)
  )
)
32.1% accuracy
39.3% accuracy
41.1% accuracy
48.2% accuracy
64.3% accuracy
82.1% accuracy
83.9% accuracy
82.1% accuracy
82.1% accuracy
83.9% accuracy
83.9% accuracy
85.7% accuracy
85.7% accuracy
91.1% accuracy
94.6% accuracy
96.4% accuracy
96.4% accuracy
96.4% accuracy
96.4% accuracy
96.4% accuracy
Equivariance error = 2.3e-06
```

Let me know if you would like me to prepare a PR.

**Comment by mariogeiger** [comment]
Hi it's simply because the main branch has changed since the last release

**Comment by muammar** [comment]
> Hi it's simply because the main branch has changed since the last release

Yes, and therefore the examples should be updated. 

Best,

**Comment by mariogeiger** [comment]
The example is up to date wrt the code in the main branch

**Comment by mariogeiger** [comment]
See the changelog https://github.com/e3nn/e3nn/blob/main/ChangeLog.md#changed

**Comment by muammar** [comment]
> See the changelog https://github.com/e3nn/e3nn/blob/main/ChangeLog.md#changed

Nice, thank you! :)
