### ISSUE TITLE
Converting pytorch conv3d layers to e3nn layers

### ISSUE THREAD

**Issue by ayushjain1144** [e3nn/e3nn#91]
I am trying to understand how should I decide the Rs_in and Rs_out values for any specific PyTorch conv3d layer I want to convert to its equivariance version.

For eg: If I want to convert nn.conv3d(in_channels=4, out_channels=4, kernel_size=5, stride=1) to its closest equivalent e3nn version, how should I go about deciding Rs_in, Rs_out, size and steps parameters for e3nn.image Convolution.

Thanks

**Comment by mariogeiger** [comment]
`e3nn.image.Convolution(Rs_in=[(4, 0)], Rs_out=[(4, 0)], size=5, stride=1)`

You can also put `Rs_out=[(1, 0), (1, 1)]` that will have the same output dimension

**Comment by mariogeiger** [comment]
Have a look at what @blondegeek wrote to explain `Rs` format https://blondegeek.github.io/e3nn_tutorial/data_types.html

**Comment by ayushjain1144** [comment]
Hello, thank you so much for your help. 
1.  I noticed that if I provide Rs_in to be [(2, 0), (2, 1), (2, 2), (2, 3)] i.e. a field of (2, 2, 2, 2) and a kernel size of 5, I get a kernel of size (64, 32, 5, 5, 5). Can you please explain how the kernel size is calculated from Rs_in? 

2.  How can I specify padding value?

3. How should I run your Convolution on a GPU? For running on GPU, I tried 

```
feat = torch.randn([5, 32, 36, 36, 36]).cuda()
net_mod  =  e3nn.image.Convolution([(32, 0)], [(64, 0)], 5, (1, 1, 1)).cuda()
feat1 = net_mod(feat).cuda()

```

I get this error: 

```
Traceback (most recent call last):
  File "tmp.py", line 34, in <module>
    main()
  File "tmp.py", line 24, in main
    feat1 = net_mod(feat).cuda()
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/e3nn-0.0.0-py3.8-linux-x86_64.egg/e3nn/image/convolution.py", line 32, in forward
    k = torch.einsum('xyzij->ijxyz', self.kernel())
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/e3nn-0.0.0-py3.8-linux-x86_64.egg/e3nn/kernel_mod.py", line 174, in forward
    R = self.R(self.radii[self.radii > self.r_eps])  # [batch, l_out * l_in * mul_out * mul_in * l_filter]
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/e3nn-0.0.0-py3.8-linux-x86_64.egg/e3nn/radial.py", line 36, in forward
    diff = x.unsqueeze(1) - self.position.unsqueeze(0)  # [batch, i, ...]
RuntimeError: expected device cpu but got device cuda:0

```

Thank you so much for your help.

**Comment by blondegeek** [comment]
Hi Ayush,

The simple, surface level answer is that an L feature is 2 * L + 1
dimensional. So you input of [(2, 0), (2, 1), (2, 2), (2, 3)] has dimension
2 * (2 * 0 + 1) + 2 * (2 * 1 + 1) + 2 * (2 * 2  + 1) + 2 * (2 * 3 + 1) = 64.

The deeper reason is the datatypes in Euclidean neural networks are not
simply floating point numbers, they are geometric tensors which have very
special rules for multiplication. For example, if you want to product
(which is the generalization of multiplication) a vector (transforms as L=1
with permuted indices y, z, x) with a kernel to get a vector — you will
have a kernel with Rs = [(1, 0), (1, 1), (1, 2)] (although we then multiply
this by the `wigner_3j_symbol` to get the tensor in the form of
[channel_in, channel_out, *sizes] rather than [channel_filter, *sizes]).
This is because these are all possible non-trivial interactions a single
vector can have with another geometric tensor that product another single
vector. For more information considering looking at Chapter 4 in Griffith’s
introduction to quantum mechanics where it discusses the “additional of
angular momentum” — while that chapter is concerned with electrons, the
mathematics is general for any geometric tensor in the L (irreducible)
basis.

As @mariogeiger recommend, the datatypes tutorial should also clarify this
a bit.

Best,
Tess

**Comment by mariogeiger** [comment]
cuda bug is fixed in e49d162798b70787c64bc493246eff26bcd7e198

**Comment by mariogeiger** [comment]
You can specify the padding like that
`Convolution(Rs_in=[(4, 0)], Rs_out=[(4, 0)], size=5, stride=1, padding=1)`

**Comment by ayushjain1144** [comment]
Thank you so much @mariogeiger and @blondegeek  for all your help.

For padding, I tried : 

```
from e3nn.image.convolution import Convolution as e3nn_conv3d
e3nn_conv3d(in_tup, out_tup,ksize, stride_tup, padding).cuda()
```

I get the following error

```
Traceback (most recent call last):
  File "archs/encoder3D.py", line 243, in <module>
    net = Net3D_NOBN(in_channel=4, pred_dim=32).cuda()
  File "archs/encoder3D.py", line 128, in __init__
    e3nn_conv3d(in_tup, out_tup,ksize, stride_tup, padding).cuda(),
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 307, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 246, in _apply
    self._buffers[key] = fn(buf)
  File "/home/sirdome/miniconda3/envs/e3nn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 307, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: an illegal memory access was encountered

```

Everything works as expected and the error goes away if I remove the padding argument. Thank you again for your help.
